export const NEXT = "NEXT";
export const BACK = "BACK";
export const ADD = "ADD";
export const EDIT = "EDIT";
export const SUBMIT = "SUBMIT";
export const DONE = "DONE";
export const CLEAR = "CLEAR";
export const SAVE="SAVE";
export const CHANGE="CHANGE"